name: push
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Specify node version...
        uses: actions/setup-node@v3
        with:
          node-version: '18.15.0'
      - name: Install Dependencies
        run: yarn install
        working-directory: ./contracts-ramp
      - name: Set up env variables...
        run: cp contracts-ramp/.env.default contracts-ramp/.env
      - name: Building...
        run: yarn build
        working-directory: ./contracts-ramp
      - name: Set-up chain...
        run: yarn chain &
        working-directory: ./contracts-ramp
        env:
          PORT: 8545
      - name: Run smart contract tests...
        run: yarn test:clean --network localhost
        working-directory: ./contracts-ramp
      - name: Run coverage
        run: yarn coverage
        working-directory: ./contracts-ramp
      - name: Check deploy
        run: yarn deploy:localhost
        working-directory: ./contracts-ramp


